M48
; DRILL file {KiCad 9.0.1} date 2026-05-15T19:31:22-0300
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-15T19:31:22-03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.000
%
G90
G05
T1
X75.5Y-141.0
T2
X78.5Y-77.0
X78.5Y-124.2
X83.5Y-61.59
X130.7Y-61.59
M30
